# Build with modules
FROM golang:1.12.1-stretch as builder
#RUN apk add --no-cache ca-certificates curl git build-base

# Get dependencies first for docker caching
WORKDIR /fhir
COPY go.mod .
COPY go.sum .
RUN go mod download

# Copy source
COPY . .
ARG GIT_COMMIT=dev

# Build fhir-server
WORKDIR /fhir/fhir-server
RUN go build -ldflags "-X main.gitCommit=$GIT_COMMIT"

# Copy into official image with MongoDB
FROM mongo:4-xenial
COPY --from=builder /fhir/fhir-server/fhir-server /
COPY --from=builder /fhir/fhir-server/config/ /config
COPY --from=builder /fhir/conformance/ /conformance
CMD ["/fhir-server", "--startMongod", "--mongodbURI", "mongodb://localhost:27017/?replicaSet=rs0", "--port", "3001", "--enableXML", "--disableSearchTotals"]
